//cac thong bao
module.exports = {
  ERROR_MESSAGE: {
    PARKING_LOT: {
      EXIST: "PARKING_LOT_EXIST",
      NOT_FOUND: "PARKING_LOT_NOT_EXIST",
      EMPTY: "PARKING_LOT_EMPTY",
      EMPTY_EXPIRATION_DATE: "EMPTY_EXPIRATION_DATE",
      EMPTY_RENTER: "EMPTY_RENTER",
      EMPTY_CAR_NUMBER: "EMPTY_CAR_NUMBER",
      NOT_STANDARD: "NONSTANDARD_EXPIRATION_DATE",
      CANT_USE: "PARKING_LOT_CANT_USE"
    },
    AUTH: {
      INVALID_TOKEN: "INVALID_TOKEN",
      PERMISSION: "PERMISSION",
      NOT_AUTHORIZED: "NOT_AUTHORIZED"
    },
    TICKET_OFFICE: {
      EXIST: "TICKET_OFFICE_EXIST",
      NOT_FOUND: "TICKET_OFFICE_NOT_EXIST",
      SAME_INFO: "TICKET_OFFICE_UPDATE_SAME_OLD_INFO",
      NOT_RENTED: "TICKET_OFFICE_NOT_RENTED",
      DATE_TIME: "DATE_TIME_END<DATE_TIME_START",
      COMPANY_BREAK: "COMPANY_NOT_COOPERATION",
      REQUEST_NULL: "REQUEST_NULL_OR_OVER_SIZE",
      COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",
      REQUEST_FAIL: "REQUEST_INVALID_FORMAT"
    },
    COMPANY: {
      EXIST: "COMPANY_EXIST",
      NOT_FOUND: "COMPANY_NOT_EXIST",
      FAIL_DELETE: "COMPANY_FAIL_DELETE",
      REQUEST_NULL: "REQUEST_NULL"
    },
    USER: {
      EXIST: "USER_EXIST",
      NOT_FOUND: "USER_NOT_EXIST",
      WRONG_PASS: "WRONG_PASSWORD",
      EMPTY_NAME: "EMPTY_NAME",
      NOT_STANDARD: {
        PASS: "NONSTANDARD_PASSWORD",
        EMAIL: "NONSTANDARD_EMAILS"
      }
    },
    ROLE: {
      NOT_FOUND: "ROLE_NOT_EXIST",
      EXIST: "ROLE_EXIST",
      EMPTY_NAME: "ROLE_NAME_EMPTY"
    }
  },
  SUCCESS_MESSAGE: {
    PARKING_LOT: {
      RENTED: "PARKING_LOT_RENTED",
      DELETED: "PARKING_LOT_DELETED"
    },
    TICKET_OFFICE: {
      PASS_CREATE: "ROOM_TICKET_CREATE_SUCCESS"
    },
    USER: {
      CREATED: "USER_CREATED",
      DELETED: "USER_DELETED",
      LOGIN: "LOGIN_SUCCESS",
      CHANGE: {
        PASS: "PASS_CHANGED",
        INFO: "INFO_CHANGED"
      }
    },
    COMPANY: {
      PASS_CREATE: "COMPANY_PASS_CREATE"
    },
    ROLE: {
      CREATED: "ROLE_CREATED"
    }
  }
};
